### ISSUE TITLE
Problem with package.json - stack trace

### ISSUE THREAD

**Issue by aioue** [sydro/atom-ansible-vault#25]
On new Atom instance `1.20.1`.
```
Unexpected token } in JSON at position 4198 in /Users/tom/.atom/packages/ansible-vault/package.json
Hide Stack Trace
SyntaxError: Unexpected token } in JSON at position 4198
    at JSON.parse (<anonymous>)
    at parseObject (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:58:25)
    at parseContentsSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:72:22)
    at Object.readFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:184:20)
    at PackageManager.module.exports.PackageManager.loadPackageMetadata (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:825:35)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:530:43)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:473:25)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:810:34
  at /Users/tom/.atom/packages/ansible-vault/package.json:1:1
```

**Comment by sydro** [comment]
Hi,
i did try to install last version of package (0.6.7) on new atom v1.20.1 (and on v1.21.0) and i didn't find the same problem.
can you reinstall the package? probably package.json is corrupt.

**Comment by aioue** [comment]
Re-install fixed it. Thank you.
