### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by yasir091** [sydro/atom-ansible-vault#36]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.12.6
**Thrown From**: [ansible-vault](https://github.com/sydro/atom-ansible-vault) package 0.7.3

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:982

TypeError: Cannot read property 'split' of undefined
    at Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:461:39)
    at result.mutateSelectedText.selection (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1387:37)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1435:92)
    at Array.map (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1435:66)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2007:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1434:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3424:26)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3395:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1433:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1386:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at ReadFileContext.callback (/packages/ansible-vault/lib/ansible-vault-utils.js:142:24)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

### Commands

```
     -0:22 ansible-vault:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
ansible-vault 0.7.3 
ask-stack 2.2.0 
atom-jinja2 0.6.0 
autocomplete-ansible 0.1.24 
file-icons 2.1.25 
foldername-tabs 0.2.4 
git-plus 8.1.0 
go-plus 5.8.6 
highlight-selected 0.14.0 
language-ansible 0.2.2 
language-ini 1.20.0 
vim-mode-plus 1.35.0 
```

**Comment by sydro** [comment]
Hi, 
i need more information to reproduce bug. 
Can you enter steps that you do?

Thanks

**Comment by sydro** [comment]
@yasir091 can you tell me more information to reproduce the bug ? Thanks

**Comment by sydro** [comment]
Feel free to reopen
