### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ebah80** [sydro/atom-ansible-vault#38]
**Describe the bug**
Using the plugin ansible-vault to open a valid vault (opening from command line without issues).

**To Reproduce**
1. Open atom
2. Select the vault file
3. Insert the vault's password

**Expected behavior**
Decrypt the vault file

**Desktop (please complete the following information):**
**Ansible version**: 2.7.2
**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ansible-vault](https://github.com/sydro/atom-ansible-vault) package 0.7.3

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'split' of undefined
    at Selection.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:534933)
    at s.mutateSelectedText.n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:15695)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:489188)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39529)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:256932)
    at ReadFileContext.callback (/packages/ansible-vault/lib/ansible-vault-utils.js:142:24)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

### Commands

```
     -6:41.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  3x -4:55.9.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -3:32.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
ansible-vault 0.7.3 
atom-json-editor 0.4.1 
compare-files 0.8.1 
highlight-selected 0.14.0 
ide-json 0.2.1 
language-terraform 0.8.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
split-diff 1.5.3 
term3 0.22.1 
```

**Comment by sydro** [comment]
Hi,
i added a few changes on the package. 
Can you try now and tell me if it's ok?

Thanks

**Comment by ebah80** [comment]
MITICO @sydro!!!
I noticed there was an update this morning and I immediately tried but with no luck :(
Now I updated to the very last one 0.7.7 and it's working properly!

GRAZIE MILLE!

**Comment by sydro** [comment]
Wonderful ! :+1: Grazie a te per la segnalazione! ;)
