### ISSUE TITLE
Error when try to encrypt or decrypt file

### ISSUE THREAD

**Issue by andrii29** [sydro/atom-ansible-vault#48]
**Describe the bug**
Error when try to decryt or encrypt file with pass, or pass from file.

**To Reproduce**
1. Create new file /tmp/2
2. Click on 'Ctrl+Alt+0' to encrypt file
3. Enter password 
`[WARNING]: Error in vault password file loading (default): Invalid vault password was provided from file (/home/andrii/.atom/packages/ansible-vault/lib/.znfk0xpjfrd.vault.temp) ERROR! Invalid vault password was provided from file (/home/andrii/.atom/packages/ansible-vault/lib/.znfk0xpjfrd.vault.temp)`

**Expected behavior**
Expect to see encrypted file

**Desktop (please complete the following information):**
 - Atom version 1.55.0
 - Ansible version 2.10.7
 - OS: Ubuntu 18.04

**Comment by andrii29** [comment]
found new error
`
/home/andrii/.atom/packages/ansible-vault/lib/ansible-vault-utils.js:55
Hide Stack Trace
TypeError: Cannot read property 'focus' of null
    at AnsibleVaultUtils.inputboxHandler (/home/andrii/.atom/packages/ansible-vault/lib/ansible-vault-utils.js:55:39)
    at /home/andrii/.atom/packages/ansible-vault/lib/ansible-vault-utils.js:270:22
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191622)
    at /usr/share/atom/resources/app/static/<embedded>:11:6718
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191622)
    at DisplayLayer.reset (/usr/share/atom/resources/app/static/<embedded>:14:85907)
    at TextEditor.update (/usr/share/atom/resources/app/static/<embedded>:11:4338)
    at TextEditor.setEditorWidthInChars (/usr/share/atom/resources/app/static/<embedded>:11:11467)
    at TextEditorComponent.updateModelSoftWrapColumn (/usr/share/atom/resources/app/static/<embedded>:11:102189)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/static/<embedded>:11:70020)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.didShow (/usr/share/atom/resources/app/static/<embedded>:11:91682)
    at TextEditorComponent.didAttach (/usr/share/atom/resources/app/static/<embedded>:11:90852)
    at HTMLElement.attachedCallback (/usr/share/atom/resources/app.asar/src/text-editor-element.js:43:25)
    at HTMLElement.activeItemChanged (/usr/share/atom/resources/app.asar/src/pane-element.js:152:22)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191622)
    at Pane.setActiveItem (/usr/share/atom/resources/app/static/<embedded>:11:456849)
    at Pane.activateItem (/usr/share/atom/resources/app/static/<embedded>:11:459097)
    at Workspace.open (/usr/share/atom/resources/app/static/<embedded>:11:432768)
`
