### ISSUE TITLE
Uncaught ReferenceError: vault_text is not defined

### ISSUE THREAD

**Issue by mordash** [sydro/atom-ansible-vault#52]
On the new Atom (Pulsar) i have this message when i try to encrypt/decrypt
My coworkers have the same error on mac or debian

Uncaught ReferenceError: vault_text is not defined

/home/user/.pulsar/packages/ansible-vault/lib/ansible-vault-utils.js:202
Hide Stack Trace
ReferenceError: vault_text is not defined
    at AnsibleVaultUtils.getSelection (ansible-vault-utils.js:202:15)
    at Object.toggleSelection (ansible-vault.js:124:31)
    at HTMLElement.ansible-vault:toggle (ansible-vault.js:36:42)
    at CommandRegistry.handleCommandEvent (/opt/Pulsar/resources/app.asar/src/command-registry.js:405:43)
    at CommandRegistry.dispatch (/opt/Pulsar/resources/app.asar/src/command-registry.js:292:17)
    at AtomEnvironment.dispatchApplicationMenuCommand (/opt/Pulsar/resources/app.asar/src/atom-environment.js:1603:19)
    at EventEmitter.outerCallback (/opt/Pulsar/resources/app.asar/src/application-delegate.js:323:47)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:

I have the version : 1.101.0-beta of Pulsar
https://github.com/pulsar-edit/pulsar/releases

Can you help us ?

**Comment by nilssonmo** [comment]
Hi do have the exact same problem. I can't get to work.
![image](https://user-images.githubusercontent.com/129489494/229046101-c1525e30-ad5d-4d13-a1e6-8348bf53bc09.png)

Uncaught ReferenceError: vault_text is not defined

/Users/mnilsson/.pulsar/packages/ansible-vault/lib/ansible-vault-utils.js:202
[Hide Stack Trace](https://github.com/sydro/atom-ansible-vault/issues/52#)
ReferenceError: vault_text is not defined
    at AnsibleVaultUtils.getSelection (ansible-vault-utils.js:202:15)
    at Object.toggleSelection (ansible-vault.js:124:31)
    at HTMLElement.ansible-vault:toggle (ansible-vault.js:36:42)
    at CommandRegistry.handleCommandEvent (/Applications/Pulsar.app/Contents/Resources/app.asar/src/command-registry.js:405:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Pulsar.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Pulsar.app/Contents/Resources/app.asar/src/window-event-handler.js:153:34)

**Comment by mordash** [comment]
up ?

**Comment by Pawel-Albatros** [comment]
Ive also start to see this problem when I moved from Atom to Pulsar. Is there any fix for it?
